### PR TITLE
Adding chromedriver 88 and geckodriver 29

### PR DESCRIPTION
**Pull request by over2take**
- Added chromdriver 88.0.4324.96
- Added geckodriver 0.29.0

### CODE REVIEW

**Comment by pelverum** [comment]
Any target date when this PR with be merged?

**Comment by mrxaxen** [comment]
Bump for a merge

**Comment by treyturner** [comment]
@jason-edstrom Hi, would you be able to help with this?

**Comment by jason-edstrom** [comment]
@treyturner Thanks for the ping. I'll review within the hour.

**Pull request merged**
