### PR TITLE
chrome-driver-version-upto-74

### PR DESCRIPTION
**Pull request by trinidad8516**
ChromeDriver version updated versions [2.46.0, 73.0.3683.68, 74.0.3729.6]

### CODE REVIEW

**Comment by trinidad8516** [comment]
@andidev is there I am not sure if you are still active with this repository, can I help keep it up to date?

**Comment by erdi** [comment]
Hey @andidev, is this project still being maintained? I depend on this metadata from https://github.com/erdi/webdriver-binaries-gradle-plugin and it would be good to know if I should start maintaining my own copy. I’m asking cause it looks like merging PRs has been a bit slow lately.

**Comment by andidev** [comment]
Sorry for the dealy, all missing drivers are now added. I'll try to merge right away in future. Thanks!

@erdi yeah I'm really sorry, been crazy busy lately. I'll merge faster in the future, I promise.

**Comment by andidev** [comment]
@erdi
If you want I could add you as a maintainer and then you can merge stuff if I am to slow. Just tell me.

**Comment by trinidad8516** [comment]
@andidev let me help you as well

**Comment by andidev** [comment]
cool, @trinidad8516 you should have received an invite now

**Comment by trinidad8516** [comment]
@andidev thanks

**Comment by erdi** [comment]
Thanks for the offer, @andidev, but I unfortunately do not have the bandwidth at the moment to properly get involved in helping out on this. Sorry.

**Comment by jay-w-jensen** [comment]
@andidev my company would like me to become a maintainer as well, if that's all right.

**Comment by andidev** [comment]
@jay-w-jensen 
Great, I added you with admin rights

**Pull request closed without merging**
