### PR TITLE
Add support for chromedriver 83.0.4103.39

### PR DESCRIPTION
**Pull request by krmaj**

### CODE REVIEW

**Comment by Mickelback00** [comment]
Is this PR waiting on any formal approvals / testing?

**Comment by unosquare-justine** [comment]
+1 this would be great to get merged soon please 🙏

**Comment by justinebateman** [comment]
+1 Would be great to get this merged soon please 🙏 

If this repo needs any help with maintainers I'm more than willing too, I use the maven plugin in a lot of my work and personal projects and it's a big big help!

**Comment by krmaj** [comment]
@jason-edstrom what do you think? Are we ready to merge?

**Comment by jason-edstrom** [comment]
Double checked everything.  Good to go.

**Pull request merged**
