### PR TITLE
Update repository-3.0.json

### PR DESCRIPTION
**Pull request by albciff**
Added chromedriver 114.0.5735.90 
* For Windows
* For Linux x64

### CODE REVIEW

**Comment by treyturner** [comment]
Hi @albciff , thanks for your contribution. Please add entries for Intel and Apple Silicon Mac at this version if you'd like this to be considered for merge. Adding only some platforms for a specific version is sure to cause confusion.

**Review by treyturner — CHANGES_REQUESTED** [review]
Hi @albciff , thanks for your contribution. Please add entries for Intel and Apple Silicon Mac at this version if you'd like this to be considered for merge. Adding only some platforms for a specific version is sure to cause confusion.

**Comment by albciff** [comment]
ok @treyturner I will add this version for Mac. Thanks for your replay.

**Comment by albciff** [comment]
Added chromedriver version 114.0.5735.90 for:

* Intel mac x64
* Apple Silicon mac x64

To this PR in response for @treyturner comments. Thanks!

**Comment by lgraf** [comment]
@treyturner Is there still something missing in this PR? Otherwise it would be great if it could be merged.

**Comment by treyturner** [comment]
@lgraf Sorry, no, my GitHub notifications are just a bit flooded! Thanks for the nudge and again for the commits.

**Review by treyturner — APPROVED** [review]

**Pull request merged**
