### PR TITLE
Add latest geckodriver

### PR DESCRIPTION
**Pull request by fhoeben**
Add geckodriver 0.19

### CODE REVIEW

**Comment by andidev** [comment]
CI files since Win 32 version of geckodriver is not released.

**Comment by fhoeben** [comment]
I see now https://github.com/mozilla/geckodriver/issues/951
Should I update pull request to leave out 32 bit windows version?

**Comment by andidev** [comment]
Not sure what the conclusion is from that issue. Until the url for the win 32 bit does not work I cannot merge this cause it will make the plugin fail in some cases.
So please remove the win 32 bit version and I'll merge this PR. Then I'll add the win 32 bit version later when it is released.

**Comment by fhoeben** [comment]
Win32 version 0.19 is removed

**Comment by andidev** [comment]
Great thanks!

**Pull request merged**
