### PR TITLE
Add edge driver for window 105.0.1343.27

### PR DESCRIPTION
**Pull request by Fung3332**

### CODE REVIEW

**Comment by treyturner** [comment]
Hi there; thanks for this. Can you please match the existing order for edgedriver, which appears to be ascending by version? You would also need to include the other platforms: mac, linux, and win32.

**Review by treyturner — CHANGES_REQUESTED** [review]
Please match existing sort order for edgedriver and include all applicable platforms

**Comment by Fung3332** [comment]
Thank you for the reply :) Updated

**Review by treyturner — APPROVED** [review]

**Comment by treyturner** [comment]
Thanks @Fung3332 !

**Pull request merged**
